# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ENCLoader
                                 A QGIS plugin
 To Load S57 files
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-28
        copyright            : (C) 2021 by Prasanth
        email                : prasanth@ntcpwc.iitm.ac.in
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ENCLoader class from file ENCLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .s57loader import ENCLoader
    return ENCLoader(iface)
